// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReederPortal.Models;

#nullable disable

namespace ReederPortal.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReederPortal.Models.Birim", b =>
                {
                    b.Property<int>("BirimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BirimID"));

                    b.Property<string>("BirimAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BirimID");

                    b.ToTable("Birims", (string)null);
                });

            modelBuilder.Entity("ReederPortal.Models.Personel", b =>
                {
                    b.Property<int>("PersonelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelID"));

                    b.Property<int>("BirimID")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CocukSayisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("DogumYer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsCalismaDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fotograf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hobi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IseBaslamaTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedeniDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mezuniyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeviyeID")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SigaraKullanimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurucuBelgesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TcKimlikNo")
                        .HasColumnType("bigint");

                    b.Property<int>("UnvanID")
                        .HasColumnType("int");

                    b.HasKey("PersonelID");

                    b.HasIndex("BirimID");

                    b.HasIndex("SeviyeID");

                    b.HasIndex("UnvanID");

                    b.ToTable("Personels", (string)null);
                });

            modelBuilder.Entity("ReederPortal.Models.Seviye", b =>
                {
                    b.Property<int>("SeviyeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeviyeID"));

                    b.Property<string>("SeviyeAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeviyeID");

                    b.ToTable("Seviyes", (string)null);
                });

            modelBuilder.Entity("ReederPortal.Models.Unvan", b =>
                {
                    b.Property<int>("UnvanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnvanID"));

                    b.Property<string>("UnvanAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnvanID");

                    b.ToTable("Unvans", (string)null);
                });

            modelBuilder.Entity("ReederPortal.Models.Personel", b =>
                {
                    b.HasOne("ReederPortal.Models.Birim", "Birim")
                        .WithMany("Personels")
                        .HasForeignKey("BirimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReederPortal.Models.Seviye", "Seviye")
                        .WithMany("Personels")
                        .HasForeignKey("SeviyeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReederPortal.Models.Unvan", "Unvan")
                        .WithMany("Personels")
                        .HasForeignKey("UnvanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Birim");

                    b.Navigation("Seviye");

                    b.Navigation("Unvan");
                });

            modelBuilder.Entity("ReederPortal.Models.Birim", b =>
                {
                    b.Navigation("Personels");
                });

            modelBuilder.Entity("ReederPortal.Models.Seviye", b =>
                {
                    b.Navigation("Personels");
                });

            modelBuilder.Entity("ReederPortal.Models.Unvan", b =>
                {
                    b.Navigation("Personels");
                });
#pragma warning restore 612, 618
        }
    }
}
